config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#home', as: 'home'
  get '/about', to: 'home#about', as: 'about'
  get '/contact', to: 'home#contact', as: 'contact'

  devise_for :users

  resources :charges, only: [:create]
  resources :followers, only: %i[create destroy]
  resources :pieces
  resources :workshops, only: [:new, :create]
end

app/models/workshop.rb
# frozen_string_literal: true

class Workshop < ApplicationRecord
  validates :bio, presence: true
  validates :bank_account, length: {is: 10}, numericality: { greater_than_or_equal_to: 10 }, presence: true
  belongs_to :user
end

app/controllers/workshops_controller.rb
# frozen_string_literal: true

class WorkshopsController < ApplicationController

  def new
    if !current_user.artist?
      @workshop = Workshop.new
      @user = current_user
    else
      redirect_to home_path
    end
  end

  def create
    @workshop = Workshop.new(workshop_params)
    @user = current_user

    if @workshop.save
      @user.artist = true
      @user.save
      redirect_to new_piece_path
    else
      render 'new'
    end
  end

  private

  def workshop_params
    params.require(:workshop).permit(:bio, :bank_account, :auto_respond_msg, :user_id)
  end
end

app/helpers/workshops_helper.rb
# frozen_string_literal: true

module WorkshopsHelper
end

app/views/workshops/new.html.erb
<div class="row">
  <div class="col-2 white-on-orange">

  </div>
  <div class="col p-5">
    <h2 class="pb-3 mb-3 border-bottom">Sell your Work </h2>

    <%= form_for :workshop, url: workshops_path, class: 'form', local: true do |form| %>

      <% if @workshop.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@workshop.errors.count, "error") %> prohibited
            this workshop from being saved:
          </h2>
          <ul>
            <% @workshop.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.hidden_field :user_id, value: @user.id %>
      <div class="field my-4">
        <%= form.label :bio, "Artist Biography" %><br />
        <%= form.text_area :bio, class: "fill text-area-high" %>
      </div>
      <div class="field my-4">
        <%= form.label :bank_account, "Bank Account Details" %><br />
        <%= form.text_field :bank_account, class: "fill" %>
      </div>
      <div class="field my-4">
        <%= form.label :auto_respond_msg, "Automatic Response Message" %><br />
        <%= form.text_area :auto_respond_msg, class: "fill text-area-high"  %>
        <br /><small>
          Give your customers an automatic response when they buy a piece,
          informing them when you will be able to get back to them.
        </small>
      </div>
      <p>
        <%= form.submit "Start your workshop", class: "btn white-on-orange" %>
      </p>
    <% end %>
    <%= link_to 'Back', home_path %>
  </div>
</div>