config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#home', as: 'home'
  get '/about', to: 'home#about', as: 'about'
  get '/contact', to: 'home#contact', as: 'contact'

  devise_for :users

  resources :charges, only: [:create]
  resources :followers, only: %i[create destroy]
  resources :pieces
  resources :workshops, only: [:new, :create]
end

app/views/layouts/shared/_footer.html.erb
<footer class="page-footer border-top bg-light text-muted d-flex justify-content-between align-items-center">
<div class="ml-3">©2019 Open Gallery by Andrew Sims and Seep Gulati</div>
<%= link_to 'Contact Us', contact_path, class: "p-3 text-dark mr-2" %>
</footer>

app/views/layouts/shared/_nav.html.erb
<nav class="navbar navbar-light navbar-expand-md bg-light">
   <%= link_to image_tag("opengallery-logo.png", height: 75, class: 'm-1 rounded'), home_path %>
  <div class="navbar-nav ml-auto">
    <% if user_signed_in? %>
    <div class="mt-1 mr-5">
      <span class="welcome text-dark mr-1">Welcome,</span>
      <span class="user-name">
        <% if [".", "Miss"].any? { |exc| current_user.full_name.split[0].include?(exc) } %>
          <%= current_user.full_name.split[1].capitalize %>
        <% else %>
          <%= current_user.full_name.split[0].capitalize %>
        <% end %>
      </span>
    </div>
      <%= link_to 'Edit your profile', edit_user_registration_path, class: "px-2 nav-link text-dark" %>
      <% if current_user.artist? %>
        <%= link_to 'Sell your work', new_piece_path, class: "px-2 nav-link text-dark" %>
      <% else %>
        <%= link_to 'Sell your work', new_workshop_path, class: "px-2 nav-link text-dark" %>
      <% end %>
      <%= link_to 'Log out', destroy_user_session_path, class: "px-2 nav-link text-dark", method: :delete %> 
   <% else %>
      <%= link_to 'Sign Up', new_user_registration_path, class: "px-2 nav-link text-dark" %>
      <%= link_to 'Login', new_user_session_path, class: "px-2 nav-link text-dark" %>
   <% end %>
 </div>
</nav>

app/views/layouts/shared/_stripe_form.html.erb
<%= form_tag charges_path do %>
  <article class="mt-5">
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <h5>This piece is valued at $<%= @piece.price %></h5>
    </label>
  </article>

  <div class="">
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Purchase <%= @piece.name %>" 
            data-amount=<%= (@piece.price * 100).to_s %> 
            data-locale="auto"></script>
  </div>
<% end %>