config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#home', as: 'home'
  get '/about', to: 'home#about', as: 'about'
  get '/contact', to: 'home#contact', as: 'contact'

  devise_for :users

  resources :charges, only: [:create]
  resources :followers, only: %i[create destroy]
  resources :pieces
  resources :workshops, only: [:new, :create]
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def home
    if current_user
      user_tags = current_user.tags
      @promo_pieces = Piece.tag_sort(user_tags)
    else
      @promo_pieces = Piece.all.sample(3)
    end
  end

  def about; end

  def contact; end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/contact.html.erb
<div class='row'>

	<div class="col-2 white-on-orange"></div>

	<div class="col">
		<h1>Send us an email.</h1>
		<%= form_tag "https://formspree.io/testuserapp6@gmail.com", method: "POST", class: "email-form" do |form| %>
			<p> 
				<%= label_tag 'name' %><br />
				<%= text_field_tag 'name' %>
			</p>
			<p> 
				<%= label_tag 'email' %><br />
				<%= text_field_tag 'email' %>
			</p>
			<p> 
				<%= label_tag 'message' %><br />
				<%= text_area_tag 'message' %>
			</p>
			<p>
				<%= submit_tag 'Send email' %>
			</p>
		<% end %>
	</div>
</div>

app/views/home/home.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="white-on-orange col-4">
      <h1 class="text-right pt-5 font-weight-bold">Open</h1>
    </div>
    <div class="col-8">
      <h1 class="pt-5 font-weight-bold">Gallery</h1>
      <h3 class="p-5">The online art gallery.</h3>
    </div>
  </div>
  <div class="d-flex flex-wrap">
    <div class="m-auto">
      <%= image_tag @promo_pieces[0].uploaded_image.service_url, size: 300, class: 'm-5 rounded cover' %>
    </div>
    <div class="m-auto">
      <%= image_tag @promo_pieces[1].uploaded_image.service_url, size: 300, class: 'm-5 rounded cover' %>
    </div>
    <div class="m-auto">
      <%= image_tag @promo_pieces[2].uploaded_image.service_url, size: 300, class: 'm-5 rounded cover' %>
    </div>
  </div>
  <div class="row mb-5">
    <%= link_to 'See all pieces', pieces_path, class: "btn white-on-orange m-auto" %>
  </div>
  <div class="row" id="about">
    <div class="col-6">
      <h2 class="text-right pt-5">Reach</h2>
      <h3 class="text-right pt-5">Bypass traditional gatekeepers and tastemakers.</h3>
      <p class="p-2">
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
        Facere dolorem id natus nemo neque odit ullam laborum porro minus! 
        Repellat, dignissimos maxime, officiis corrupti deleniti commodi eos molestias 
        consequuntur sequi, iure magni sapiente consectetur rem repudiandae blanditiis 
        nesciunt perferendis rerum aliquid. Sequi eaque natus quaerat, doloribus rerum 
        veniam ratione adipisci sapiente impedit nisi minima, deserunt optio, assumenda 
        aperiam asperiores vitae.
      </p>
    </div>
    <div class="col-6 white-on-orange pt-5 font-weight-bold">
      <h2>your audience.</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-4 white-on-orange">
      <h2 class="text-right pt-5 font-weight-bold">Collect</h2>
    </div>
    <div class="col-8">
      <h2 class="pt-5">fine art.</h2>
      <h3 class="pt-5">Don't limit yourself by geography.</h3>
      <p class="p-2">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
        Pariatur illum repellendus rem, quo quis vitae laboriosam qui eum 
        obcaecati id minima explicabo voluptate maxime odio ipsa consequuntur 
        eveniet maiores consequatur sint praesentium inventore! Magnam ea impedit 
        quam sunt, delectus consequuntur quas ipsa incidunt animi odit commodi 
        adipisci at nisi id explicabo possimus nam quia esse quis unde minus. 
        Recusandae, cum sequi deserunt quis sapiente illum quasi quas est nulla quam, 
        facilis perspiciatis enim commodi? Incidunt cumque sint recusandae architecto 
        officiis ducimus id ullam nihil voluptate sed laborum sunt dolores quidem 
        pariatur voluptates repudiandae necessitatibus mollitia dolore maxime veniam, 
        aspernatur temporibus?
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-9">
      <h2 class="text-right pt-5">Support</h2>
      <h3 class="text-right pt-5">Keep up to date with your favourite creators.</h3>
      <p class="p-2">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi blanditiis 
        debitis dolorem illum! In illum nostrum ducimus, voluptate sint veniam labore 
        impedit aut cum cupiditate error non culpa officiis, vel doloremque 
        oluptatibus recusandae, ipsa atque dolor corrupti facere dolore voluptas 
        dicta! Ut, ipsa. Fugit adipisci sit exercitationem optio, eius, praesentium, 
        hic iusto nostrum voluptates maiores expedita reiciendis voluptatum. Repudiandae 
        maxime laudantium rerum optio maiores culpa nesciunt aperiam consectetur 
        minima repellendus?
      </p>
    </div>
    <div class="col-3 white-on-orange">
      <h2 class="pt-5 font-weight-bold">gifted artists.</h2>
    </div>
  </div>
</div>