config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#home', as: 'home'
  get '/about', to: 'home#about', as: 'about'
  get '/contact', to: 'home#contact', as: 'contact'

  devise_for :users

  resources :charges, only: [:create]
  resources :followers, only: %i[create destroy]
  resources :pieces
  resources :workshops, only: [:new, :create]
end

app/models/piece.rb
# frozen_string_literal: true

class Piece < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true
  validates :materials, presence: true
  validates :dimensions, presence: true
  validates :description, presence: true
  validates :uploaded_image, presence: true

  belongs_to :user, optional: true
  belongs_to :workshop

  has_one_attached :uploaded_image

  def self.tag_sort(user_tags)
    # Sort all pieces into three tiers: total match, partial match and no match between tags
    pieces_total_match = Piece.all.select { |p| p.tags.all? { |tag| user_tags.any? tag } }

    pieces_partial_match = Piece.all.select do |p|
      p.tags.any? { |tag| user_tags.any? tag } && !pieces_total_match.include?(p)
    end

    pieces_no_match = Piece.all.select do |p|
      !pieces_total_match.include?(p) && !pieces_partial_match.include?(p)
    end

    # Concatenate these tiers into the sorted array of pieces
    pieces_total_match + pieces_partial_match + pieces_no_match
  end

  def self.favourite_sort(piece_arr, user_id)
    # Takes an array of pieces and brings pieces by favourited artists to the top
    piece_arr.partition do |p|
      Follower.find_by(workshop_id: p.workshop.id, user_id: user_id)
    end.flatten
  end
end

app/controllers/pieces_controller.rb
# frozen_string_literal: true

class PiecesController < ApplicationController
  def index
    if current_user # Sorting only occurs if logged in
      user_tags = current_user.tags
      pieces = Piece.tag_sort(user_tags)
      @pieces = Piece.favourite_sort(pieces, current_user.id)
    else
      @pieces = Piece.all.shuffle
    end
  end

  def show
    @piece = Piece.find(params[:id])
    @artist = @piece.workshop.user
    if current_user
      @follower = Follower.find_by(workshop_id: @piece.workshop.id, user_id: current_user.id)
      @follower ||= Follower.new
    end
    cookies.encrypted[:piece_id] = params[:id]
  end

  def new
    if current_user&.artist?
      @piece = Piece.new
      @user = current_user
      @workshop = Workshop.find_by(user_id: @user.id)
    else
      redirect_to home_path
    end
  end

  def edit
    if current_user&.artist?
      @piece = Piece.find(params[:id])
      @user = current_user
      @workshop = Workshop.find_by(user_id: @user.id)
    else
      redirect_to home_path
    end
  end

  def create
    @piece = Piece.new(piece_params)

    if @piece.save
      redirect_to @piece
    else
      render 'new'
    end
  end

  def update
    @piece = Piece.find(params[:id])

    if @piece.update(piece_params)
      redirect_to @piece
    else
      render 'edit'
    end
  end

  def destroy
    @piece = Piece.find(params[:id])
    @piece.uploaded_image.purge
    @piece.destroy

    redirect_to pieces_path
  end

  private

  def piece_params
    params.require(:piece).permit(:name, :description, :price, :materials, :dimensions, :workshop_id, :uploaded_image, tags: [])
  end
end

app/helpers/pieces_helper.rb
# frozen_string_literal: true

module PiecesHelper
end

app/views/pieces/edit.html.erb
<h1>Edit Piece</h1>
<%= form_with(model: @piece, class: 'form', local: true, multipart: true) do |form| %>
<% if @piece.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this piece from being saved:
      </h2>
      <ul>
        <% @piece.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :workshop_id, value: @workshop.id %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
 <p>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </p>

 <p>
    <%= form.label :materials %><br>
    <%= form.text_field :materials %>
  </p>

</div>
 <p>
    <%= form.label :dimensions %><br>
    <%= form.text_field :dimensions %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :tags %><br>
    <%= form.text_field :tags, multiple: true %>
    <%= form.text_field :tags, multiple: true %>
    <%= form.text_field :tags, multiple: true %>
  </p>
  
  <p>
    <%= form.label :uploaded_image %><br>
    <%= form.file_field :uploaded_image %>
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', @piece %>

app/views/pieces/home.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="white-on-orange col-4">
      <h1 class="text-right pt-5 font-weight-bold">Open</h1>
    </div>
    <div class="col-8">
      <h1 class="pt-5 font-weight-bold">Gallery</h1>
      <h3 class="p-5">An online art gallery and social media platform.</h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= image_tag "lakse.jpg", size: 300, class: 'm-5 rounded' %>
    </div>
    <div class="col">
      <%= image_tag "wessels.jpg", size: 300, class: 'm-5 rounded' %>
    </div>
    <div class="col">
      <%= image_tag "babybirthday.jpg", size: 300, class: 'm-5 rounded' %>
    </div>
  </div>
  <div class="row">
    <%= link_to url: pieces_path, class: "col-2 offset-5" do %>
      <p class="btn btn-success center">View more pieces</p>
    <% end %>
  </div>
  <div class="row">
    <div class="col-6">
      <h2 class="text-right pt-5 font-weight-bold">Reach</h2>
      <h3 class="text-right pt-5">Bypass traditional gatekeepers and tastemakers.</h3>
      <p class="p-2">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere dolorem id natus nemo neque odit ullam laborum porro minus! Repellat, dignissimos maxime, officiis corrupti deleniti commodi eos molestias consequuntur sequi, iure magni sapiente consectetur rem repudiandae blanditiis nesciunt perferendis rerum aliquid. Sequi eaque natus quaerat, doloribus rerum veniam ratione adipisci sapiente impedit nisi minima, deserunt optio, assumenda aperiam asperiores vitae.</p>
    </div>
    <div class="col-6 white-on-orange pt-5 font-weight-bold">
      <h2>your audience.</h2>
    </div>
  </div>
</div>

app/views/pieces/index.html.erb
<div class="container-fluid">
  <div class="d-flex flex-wrap mt-5 justify-content-around">
    <% @pieces.each do |piece| %>
      <div class="card mb-5 p-3 shadow col-md-5" style="height: 100vh;">
        <% if piece.uploaded_image.attached? %>
          <%= image_tag piece.uploaded_image.service_url, class: "card-img-top cover" %>
        <% end %> 
        <div class="card-body">
          <div class="row pb-3">
            <div class="col-md-7">
              <h3 class="card-title"><%= piece.name %></h3>
            </div>
            <div class="col-md">
              <p class="text-muted text-right">by <%= piece.workshop.user.full_name %></p>
              <% piece.tags.each do |tag| %>
                <div class="badge badge-light float-right border"><%= tag %></div><br />
              <% end %>
            </div>
          </div>
          <%= link_to 'More Info', piece_path(piece.id), class: 'btn white-on-orange' %>
          <% if piece.sold? %>
            <span class="badge badge-danger">Sold!</span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pieces/new.html.erb
<div class="row">
  <div class="col-3 white-on-orange">
  </div>
  <div class="col p-5">
    <h2 class="pb-3 mb-3 border-bottom">Add your piece</h2>

    <%= form_with scope: :piece, url: pieces_path, local: true, multipart: true do |form| %>
      
      <% if @piece.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@piece.errors.count, "error") %> prohibited
            this piece from being saved:
          </h2>
          <ul>
            <% @piece.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.hidden_field :workshop_id, value: @workshop.id %>

      <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
      </div>
    
      <div>
        <%= form.label :price %><br>
        <%= form.text_field :price %>
      </div>

      <div>
        <%= form.label :materials %><br>
        <%= form.text_field :materials %>
      </div>

      <div>
        <%= form.label :dimensions %><br>
        <%= form.text_field :dimensions %>
      </div>

      <div>
        <%= form.label :description %><br>
        <%= form.text_area :description %>
      </div>

      <div>
        <%= form.label :tags %><br>
        <%= form.text_field :tags, multiple: true %>
        <%= form.text_field :tags, multiple: true %>
        <%= form.text_field :tags, multiple: true %>
      </div>
      
      <div>
        <%= form.label :uploaded_image %><br>
        <%= form.file_field :uploaded_image %>
      </div>

      <div>
        <%= form.submit "Save Piece", class: "btn white-on-orange" %>
      </div>
    <% end %> 

    <%= link_to 'Back', home_path %>
  </div>
</div>

app/views/pieces/show.html.erb
<script>
  function toggleHeart(button) {
    button.classList.toggle("fas");
    button.classList.toggle("far");
    button.classList.toggle("text-danger");
  }

  function favorArtist() {
    let button = document.getElementsByClassName("like-button")[0];
    
    if (button.classList.contains("fas")) {
      toggleHeart(button)
      // Destroy the Follower record
      $.ajax({
      url: '/followers/<%= @follower ? @follower.id : 0 %>',
      data: { 
        authenticity_token: $('[name="csrf-token"]')[0].content,
        id: <%= (@follower.id ? @follower.id : 0) if @follower %>,  
      },
      method: 'DELETE'
      })
    
    } else {
      toggleHeart(button)
      // Create a Follower record
      $.ajax({
      url: '/followers',
      data: { 
        authenticity_token: $('[name="csrf-token"]')[0].content,
        follower: {
          user_id: <%= current_user.id if current_user %>,
          workshop_id: <%= @piece.workshop.id %>,
          }
      },
      method: 'POST'
      }).then(() => {document.location.reload()}
      )
    }
  }
</script>

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3 white-on-orange">
      <% if current_user %>
      <i class="<% if @follower.id %>fas text-danger <% else %> far <% end %>fa-heart like-button btn btn-light" onclick="favorArtist()"></i>
      <% end %>
      <%= image_tag @piece.uploaded_image.service_url, width: "500", class: 'm-5 pt-4' %>
    </div>
    <div class="col-7 offset-2">
      <h2 class="m-3 text-center"><%= @piece.name %> 
      <br /><span class="text-orange">by</span> <%= @artist.full_name %></h2>
      <p class="text-right mt-5"><%= @piece.description %></p>
      <p class="text-right"><%= @piece.materials %></p>
      <p class="text-right"><%= @piece.dimensions %></p>
      <% @piece.tags.each do |tag| %>
        <span class="badge badge-light align-right border float-right"><%= tag %></span>
      <% end %>
      <% if @piece.sold? %>
        <br /><p class="text-right">Sold to <%= @piece.user.full_name %></p>
      <% else %>
        <% if user_signed_in? %>
          <div class="text-right">
            <br /><button type="button" class="btn white-on-orange" data-toggle="modal", data-target="#contact">
              Contact the artist
            </button>
          </div>
          <div class="text-center">
            <%= render "layouts/shared/stripe_form" %>
          </div>
        <% end %>
      <% end %>
      <% if current_user && current_user.id == @artist.id %>
        <p class="text-right"><%= link_to 'Edit', edit_piece_path(@piece.id) %></p>
        <p class="text-right"><%= link_to 'Delete', piece_path, method: :delete %></p>
      <% else %>
      <% end %>
    </div>
  </div>
</div>


<div class="modal fade" id="contact" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Write to <%= @artist.full_name %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
      <%= form_tag "https://formspree.io/testuserapp6@gmail.com", method: "POST", class: "d-flex flex-column align-items-around" do %>
        <div class="md-form mb-3">
					<%= label_tag 'name' %><br />
					<%= text_field_tag 'name', value="#{@current_user.full_name if user_signed_in?}", style: "width: 100%;" %>
        </div>

        <div class="md-form mb-3">
					<%= label_tag 'email' %><br />
					<%= text_field_tag 'email', value="#{@current_user.email if user_signed_in?}", style: "width: 100%;" %>
        </div>

        <div class="md-form mb-3">
					<%= label_tag 'subject' %><br />
					<%= text_field_tag 'subject', value="About your artwork #{@piece.name}", style: "width: 100%;" %> 
        </div>

        <div class="md-form">
					<%= label_tag 'message' %><br />
					<%= text_area_tag 'message', placeholder="", style: "width: 100%;" %>
        </div>

      </div>
      <div class="modal-footer d-flex justify-content-center">
					<%= submit_tag 'Send email!', class: 'btn white-on-orange' %>
      </div>
      <% end %>
    </div>
  </div>
</div>